Repository dippynark/kfmt, pull requests merged in 2021-01, with the labels that each got.

#4 Test
  .gitignore
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/M

#5 Improve flags
  Makefile
  README.md
  main.go
Labels: approved, size/L

#14 Add new line
  main.go
Labels: approved, ok-to-test, size/XS
